name       : akonadi-notes
version    : 20.12.0
release    : 41
source     :
    - https://cdn.download.kde.org/stable/release-service/20.12.0/src/akonadi-notes-20.12.0.tar.xz : d6237903b79d31e0a685d955c77fc216ce3ac0fcefeaec3e9326ad80d008eccd
homepage   : https://kde.org/
license    : LGPL-2.1-or-later
component  : desktop.library
summary    : Libraries and daemons to implement management of notes in Akonadi
description: |
    Libraries and daemons to implement management of notes in Akonadi.
builddeps  :
    - pkgconfig(Qt5Xml)
    - extra-cmake-modules
    - kcompletion-devel
    - ki18n-devel
    - kitemmodels-devel
    - kmime-devel
    - kxmlgui-devel
    - libboost-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
