name       : akonadi-notes
version    : 20.08.1
release    : 38
source     :
    - https://cdn.download.kde.org/stable/release-service/20.08.1/src/akonadi-notes-20.08.1.tar.xz : afc0cdba349f0b2edece44221a7c3c532d07251ec51f05994e83a1d79c4f50fc
homepage   : https://kde.org/
license    : LGPL-2.1-or-later
component  : desktop.library
summary    : Libraries and daemons to implement management of notes in Akonadi
description: |
    Libraries and daemons to implement management of notes in Akonadi.
builddeps  :
    - pkgconfig(Qt5Xml)
    - extra-cmake-modules
    - kcompletion-devel
    - ki18n-devel
    - kitemmodels-devel
    - kmime-devel
    - kxmlgui-devel
    - libboost-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
