name       : akonadi-notes
version    : 22.12.1
release    : 62
source     :
    - https://cdn.download.kde.org/stable/release-service/22.12.1/src/akonadi-notes-22.12.1.tar.xz : 65c72aa62e7057e556a729714fdd12ac0fe5d2f3535530c8c8cae53b9845a386
homepage   : https://kde.org/
license    : LGPL-2.1-or-later
component  : desktop.library
summary    : Libraries and daemons to implement management of notes in Akonadi
description: |
    Libraries and daemons to implement management of notes in Akonadi.
builddeps  :
    - kcodecs-devel
    - ki18n-devel
    - kmime-devel
    - libboost-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
