name       : akonadi-notes
version    : 19.12.1
release    : 30
source     :
    - https://cdn.download.kde.org/stable/release-service/19.12.1/src/akonadi-notes-19.12.1.tar.xz : cf8059cb14eca880c09fc83285576b4d03a8edf0799cebdf42d59084bb6904ca
homepage   : https://kde.org/
license    : LGPL-2.1-or-later
component  : desktop.library
summary    : Libraries and daemons to implement management of notes in Akonadi
description: |
    Libraries and daemons to implement management of notes in Akonadi.
builddeps  :
    - pkgconfig(Qt5Xml)
    - extra-cmake-modules
    - kcompletion-devel
    - ki18n-devel
    - kitemmodels-devel
    - kmime-devel
    - kxmlgui-devel
    - libboost-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
