name       : akonadi-notes
version    : 18.04.0
release    : 9
source     :
    - https://cdn.download.kde.org/stable/applications/18.04.0/src/akonadi-notes-18.04.0.tar.xz : 3b807cbc616db85f2d79e85c897c04351f83985152ed531c46067a290b0a192a
license    :
    - GPL-2.0
    - LGPL-2.1
component  : desktop.library
optimize   : lto
summary    : Libraries and daemons to implement management of notes in Akonadi.
description: |
    Libraries and daemons to implement management of notes in Akonadi.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Xml)
    - akonadi-devel
    - extra-cmake-modules
    - kcompletion-devel
    - ki18n-devel
    - kitemmodels-devel
    - kmime-devel
    - kxmlgui-devel
    - libboost-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
