name       : akonadi-notes
version    : 23.04.0
release    : 63
source     :
    - https://cdn.download.kde.org/stable/release-service/23.04.0/src/akonadi-notes-23.04.0.tar.xz : c4f64ff89816ae14d8fc93e02ab0971d9beda6ae69dd710443d4efd0d94ff93f
homepage   : https://kde.org/
license    : LGPL-2.1-or-later
component  : desktop.library
summary    : Libraries and daemons to implement management of notes in Akonadi
description: |
    Libraries and daemons to implement management of notes in Akonadi.
builddeps  :
    - kcodecs-devel
    - ki18n-devel
    - kmime-devel
    - libboost-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
