name       : akonadi-notes
version    : 20.08.0
release    : 37
source     :
    - https://cdn.download.kde.org/stable/release-service/20.08.0/src/akonadi-notes-20.08.0.tar.xz : aeb348d6af30e8775d60cab0894634c6e5ac95a3baf97f69407602dea5944525
homepage   : https://kde.org/
license    : LGPL-2.1-or-later
component  : desktop.library
summary    : Libraries and daemons to implement management of notes in Akonadi
description: |
    Libraries and daemons to implement management of notes in Akonadi.
builddeps  :
    - pkgconfig(Qt5Xml)
    - extra-cmake-modules
    - kcompletion-devel
    - ki18n-devel
    - kitemmodels-devel
    - kmime-devel
    - kxmlgui-devel
    - libboost-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
