name       : akonadi-notes
version    : 19.08.3
release    : 28
source     :
    - https://cdn.download.kde.org/stable/applications/19.08.3/src/akonadi-notes-19.08.3.tar.xz : 7c701d8a032161f9a58a55dd7e71a9a261fed8044ddc59d6d5f04bb742801b65
license    : LGPL-2.1-or-later
component  : desktop.library
summary    : Libraries and daemons to implement management of notes in Akonadi
description: |
    Libraries and daemons to implement management of notes in Akonadi.
builddeps  :
    - pkgconfig(Qt5Xml)
    - extra-cmake-modules
    - kcompletion-devel
    - ki18n-devel
    - kitemmodels-devel
    - kmime-devel
    - kxmlgui-devel
    - libboost-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
