name       : akonadi-notes
version    : 21.08.0
release    : 50
source     :
    - https://cdn.download.kde.org/stable/release-service/21.08.0/src/akonadi-notes-21.08.0.tar.xz : 690b267946bf8fba2272f1ed26c4f4c43e977875205502ff68c19c2e0744a191
homepage   : https://kde.org/
license    : LGPL-2.1-or-later
component  : desktop.library
summary    : Libraries and daemons to implement management of notes in Akonadi
description: |
    Libraries and daemons to implement management of notes in Akonadi.
builddeps  :
    - kcodecs-devel
    - ki18n-devel
    - kmime-devel
    - libboost-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
