name       : akonadi-notes
version    : 22.04.3
release    : 60
source     :
    - https://cdn.download.kde.org/stable/release-service/22.04.3/src/akonadi-notes-22.04.3.tar.xz : b4525d32dcd2559eaa2f5ec5a86c4a4c17fe7ab14ffd019d30586f78c249495f
homepage   : https://kde.org/
license    : LGPL-2.1-or-later
component  : desktop.library
summary    : Libraries and daemons to implement management of notes in Akonadi
description: |
    Libraries and daemons to implement management of notes in Akonadi.
builddeps  :
    - kcodecs-devel
    - ki18n-devel
    - kmime-devel
    - libboost-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
