name       : akonadi-notes
version    : 21.12.1
release    : 55
source     :
    - https://cdn.download.kde.org/stable/release-service/21.12.1/src/akonadi-notes-21.12.1.tar.xz : db4a8435ae63f935d05d60313c849652c7e61dfe2d88efbfc9a56328cfaa2cd1
homepage   : https://kde.org/
license    : LGPL-2.1-or-later
component  : desktop.library
summary    : Libraries and daemons to implement management of notes in Akonadi
description: |
    Libraries and daemons to implement management of notes in Akonadi.
builddeps  :
    - kcodecs-devel
    - ki18n-devel
    - kmime-devel
    - libboost-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
