name       : akonadi-notes
version    : 18.08.2
release    : 15
source     :
    - https://cdn.download.kde.org/stable/applications/18.08.2/src/akonadi-notes-18.08.2.tar.xz : 3fd3eb69e3780547a720692865d86c6ff966a83cfa16f2d574762049a2492ee4
license    :
    - GPL-2.0
    - LGPL-2.1
component  : desktop.library
summary    : Libraries and daemons to implement management of notes in Akonadi
description: |
    Libraries and daemons to implement management of notes in Akonadi.
builddeps  :
    - pkgconfig(Qt5Xml)
    - akonadi-devel
    - extra-cmake-modules
    - kcompletion-devel
    - ki18n-devel
    - kitemmodels-devel
    - kmime-devel
    - kxmlgui-devel
    - libboost-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
