name       : akonadi-notes
version    : 19.08.2
release    : 27
source     :
    - https://cdn.download.kde.org/stable/applications/19.08.2/src/akonadi-notes-19.08.2.tar.xz : 64684c50d06664d8ccda098f8bfa536e861e4938c8f27688ef97653f7788fdde
license    : LGPL-2.1-or-later
component  : desktop.library
summary    : Libraries and daemons to implement management of notes in Akonadi
description: |
    Libraries and daemons to implement management of notes in Akonadi.
builddeps  :
    - pkgconfig(Qt5Xml)
    - akonadi-devel
    - extra-cmake-modules
    - kcompletion-devel
    - ki18n-devel
    - kitemmodels-devel
    - kmime-devel
    - kxmlgui-devel
    - libboost-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
